applications:
    - name: argo-apps
      namespace: default
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      project: default
      source:
        path: apps
        repoURL: https://github.com/saluteslim/tera-eks.git
        targetRevision: main
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
projects: []
applicationsets: []
extensions: []