apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sock-shop
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/saluteslim/tera-pat.git
    targetRevision: main
    ref: exam
    path: $exam/apps/apps-values/manifests/    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true